### ISSUE TITLE
Creating Milestone 2 Report 

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#151]
- [x] Create the page
- [x] Add links to individual reports 
- [x] Add the page to the side bar
- [x] Arrange general layout
- [x] Write reports under headers: 1.1. Introduction/Project Description, 2.1. Evaluation of Tools, 2.1.5. React.js, 2.2.1. Team Meetings

**Comment by sudek0** [comment]
Done. Can be seen [here](https://github.com/bounswe/bounswe2023group8/wiki/Milestone-2-Report).
