### ISSUE TITLE
Fixing Project Plan

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#309]
We need to fix our project plan according to the feedback.

- [x] Move Dockerization to the period before milestone 1. We already deployed our project. We just need to fix the plan for documentation's sake.
- [x] Assign tasks to resources(team members)
- [x] Add milestone 2 and 3

**Comment by EgemenKaplan** [comment]
The new [Project plan](https://github.com/bounswe/bounswe2023group8/wiki/Project-Plan) is ready.
