### ISSUE TITLE
Creating Individual Report for Milestone 1

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#313]
- [x] Create Individual Contribution Report Page
- [x] Add it to sidebar
- [x] Fill it accordingly

**Comment by MericKeskin** [comment]
Completed my individual contribution report for Milestone 1
