### ISSUE TITLE
Create Customer Milestone Report 1

### ISSUE THREAD

**Issue by bakikucukcakiroglu** [bounswe/bounswe2023group8#322]
- [x] Add Software Requirements Specification 
- [x] Add UML diagrams
- [x] Add Scenerios and Mockups
- [x] Add Project Plan, Communication Plan, Responsibility Assignment Matrix
- [x] Add Weekly Reports
- [x] Add Milestone Review
- [x] Add Individual Contribution Reports
- [x] Add the pre-release version of the software

**Comment by bakikucukcakiroglu** [comment]
https://github.com/bounswe/bounswe2023group8/wiki/Customer-Milestone-1-Deliverables
