### ISSUE TITLE
Orkun's Research

### ISSUE THREAD

**Issue by orkunkilic** [bounswe/bounswe2023group8#4]
**Problem**
I need to find an inspect a repository in terms of its documentation, issues and PRs.

**TODO**
- [x] Select a repo to inspect
- [x] Read documentation, issue templates, and PRs (templates, reviews, CI/CD)
- [x] Write the research page

**Comment by orkunkilic** [comment]
Update on TODO 1:
    I selected [Subnet-EVM](https://github.com/ava-labs/subnet-evm) repository to inspect. It is a custom Ethereum Virtual Machine implementation.

**Comment by orkunkilic** [comment]
Finished the report for my [research](https://github.com/bounswe/bounswe2023group8/wiki/Research) page. Closing.
