### ISSUE TITLE
Create Individual Contribution Report for Milestone 2

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#512]
Create an individual contribution report in the following format:

- [x] Member: Name

- [x] Responsibilities: The overall description of responsibilities assigned to you.

- [x] Main contributions: The overall description of your contributions to the project until
Customer Milestone 2.

- [x] Code-related significant issues: Your issues (that you have resolved or reviewed
significantly) that contribute to the code base demonstrated during the demo.

- [x] Management-related significant issues: Your issues (that you have resolved or
reviewed significantly) that contribute to the management of the project. 

- [x] Pull requests: You have created, merged, and reviewed. Please also briefly summarize what
the conflict was (if you had any) and how it was resolved regarding the pull requests you
have reviewed.

- [x] Additional information: Mention any additional task you have performed that is not listed
above.

**Comment by MericKeskin** [comment]
Completed the contribution report.
